### ISSUE TITLE
What does client.unsubscribe() do?

### ISSUE THREAD

**Issue by tkurki** [SignalK/signalk-js-client#71] opened 2020-04-07 16:33 UTC
It is mentioned in the readme example, what does it do?

With code like this with 2 subscriptions it sends one unsubscribe with bogus data.

```
const Client = require('./').Client


const client = new Client({
    hostname: 'localhost',
    port: 3000,
    useTLS: false
})
client.on('connectionInfo', x => console.log(x))
client.connect().then(() =>
    client.subscribe({
        context: 'vessels.self',
        subscribe: [{ path: 'navigation.position' }]
    }, 'a')
).then(() =>
    client.subscribe({
        context: 'vessels.self',
        subscribe: [{ path: 'navigation.speedOverGround' }]
    }, 'b')
).then(s => {
    s.unsubscribe()
}).catch(e => console.error(e))
```

**Comment by fabdrol** [comment] 2020-04-15 09:49
Duplicate of https://github.com/SignalK/signalk-js-client/issues/72, please continue discussion there. I'm closing this one.

**Comment by tkurki** [comment] 2020-04-15 17:48
Not a duplicate - can you describe what it does

**Comment by fabdrol** [comment] 2020-04-15 18:19
It sends an unsubscribe command to the server (although that was wrong, see the other issue and my PR fixing it) and removes related (delta) message listeners. Then it removes the subscription from the map of subscriptions. See https://github.com/SignalK/signalk-js-client/blob/master/src/lib/client.js#L293

**Comment by fabdrol** [comment] 2020-04-20 21:20
@tkurki in #76 the behaviour is simpler, it just sends an `unsubscribe` command to the server. Closing, as your question has been answered.

**Closed as completed by fabdrol** 2020-04-20 21:20 UTC
